### ISSUE TITLE
[EPIC] Implement protocol decorators and helpers

### ISSUE THREAD

**Issue by leinlawun** [fincubator/ethereum_gateway#34]
- [ ] Implement the @api_client and @api_server decorators (#31)
- [ ] Implement JSON-RPC interaction (#32)
- [ ] Implement ZeroMQ interaction (#33)
